urls.py
from django.conf.urls.defaults import patterns, include, url

from pr1.autos.views import *
from pr1.autos2.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django.conf import settings

urlpatterns = patterns('',
    ('^$',start),
	(r'^preview/(\d)/(\d)/$', preview),
    (r'^search/$', start),
	#(r'^add/man/$', start),
	#(r'^add/mod/$', start),
    (r'^prototype.js$', prototype),
    (r'^add/itm/$', item_add_form),
    (r'^feeds/models-by-man/(\d+)/$', feed_models),
    (r'^edit/itm/$', item_edit_form),
    (r'^delete/itm/$', delete_item),
    (r'^accounts/login/$',  login),
    (r'^accounts/logout/$', logout),
    (r'^catalog2/$', catalog),
    (r'^catalog2/add/$', catalog_add),
    (r'^catalog2/edit/(\d+)/$', catalog_edit),
    (r'^catalog2/del/(\d+)/$', catalog_delete),
    # Examples:
    # url(r'^$', 'pr1.views.home', name='home'),
    # url(r'^pr1/', include('pr1.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
)

autos/forms.py
# -*- coding: utf-8 -*-
from django import forms
from autos.models import *

class DynamicChoiceField(forms.ChoiceField): 
    def clean(self, value): 
        return value

class AItemForm(forms.Form):
    aid = forms.IntegerField(widget=forms.HiddenInput(), initial=-1)
    amanufact = forms.ModelChoiceField(queryset=AManufact.objects.all(), label='Производитель')
    amodel = DynamicChoiceField(label='Модель')
    color = forms.CharField(label='Цвет')
    hp = forms.IntegerField(label='Мощность')
    mfdate = forms.DateField(label='Дата выпуска')

autos2/forms.py
# -*- coding: utf-8 -*-
from django import forms
from autos2.models import *

class TruckForm(forms.Form):
    item_id = forms.IntegerField(widget=forms.HiddenInput(), initial=-1)
    #id_type = forms.ChoiceField(widget=forms.HiddenInput(), initial=0)
    modelname = forms.CharField(label='Производитель')
    capacity = forms.IntegerField(label='Грузоподъёмность')
    horsepower = forms.IntegerField(label='Сила')

class CarForm(forms.Form):
    item_id = forms.IntegerField(widget=forms.HiddenInput(), initial=-1)
    #id_type = forms.ChoiceField(widget=forms.HiddenInput(), initial=0)
    modelname = forms.CharField(label='Производитель')
    body_type = forms.CharField(label='Тип кузова')
    speed = forms.IntegerField(label='Скорость')
    doors = forms.IntegerField(label='Количество дверей')

class UniversalForm(forms.Form):
    item_id = forms.IntegerField(widget=forms.HiddenInput(), initial=-1)
    id_type = forms.ChoiceField(widget=forms.HiddenInput(), initial=0)
    modelname = forms.CharField(label='Производитель')
    capacity = forms.IntegerField(label='Грузоподъёмность')
    horsepower = forms.IntegerField(label='Сила')
    body_type = forms.CharField(label='Тип кузова')
    speed = forms.IntegerField(label='Скорость')
    doors = forms.IntegerField(label='Количество дверей')

templates/aitem_form.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<HTML>
    <HEAD>
    <base target="main">
    <TITLE>123456789012345678901234567890123456789</TITLE>

<script LANGUAGE="JavaScript" src="/prototype.js" type="text/javascript"></script>

<SCRIPT LANGUAGE="JavaScript">
<!--

function FilterModels() {

	var modelList = $('id_amodel');
	for (var count = modelList.options.length-1; count >-1; count--){
		modelList.options[count] = null;
	}
	modelList.options[0] = new Option('Loading...', '-1', false, false);
	modelList.disabled = true;

	var makeList = $('id_amanufact');
	var make_id = makeList.options[makeList.selectedIndex].value;
	if (make_id > 0) {
		new Ajax.Request('/feeds/models-by-man/' + make_id + '/', { 
			method:'get',
  			onSuccess: function(transport) {
				var response = transport.responseText || 'no response text';
				var kvpairs = response.split("/");
                var sel_val = 1;
				for (i=0; i<kvpairs.length - 1; i++) {
					m = kvpairs[i].split("*");
					var option = new Option(m[1], m[0], false, false);
					modelList.options[i] = option;
					if (m[1] == "{{ amodel1.name }}"){
						sel_val = i + 1;
					}
				}
				modelList.disabled = false;
				if (sel_val > 0) {
					modelList.value = sel_val;
				}
                       },
            onFailure: function(transport){
				alert('An error occured trying to filter the model list.');
				modelList.options[0] = new Option('Other', '0', false, false);
				modelList.disabled = false;
			           }
			});
	}
	else {
		modelList.options[0] = new Option('Select Make', '-1', false, false);
		modelList.disabled = true;
	}
}


//-->
</SCRIPT>

    <title>Add item</title>
</head>
<body>
    <h1>Add item</h1>

    <form action="/{{ action }}/itm/" method="post">{% csrf_token %}
	{{ form.aid }}
        <table>
            <tr><th><label for="id_amanufact">Производитель:</label></th><td><select name="amanufact" id="id_amanufact" onchange=FilterModels()>
			{% for man in  amanufact1 %}
				<option value= "{{ man.id }}" 
				{% if man == amanufact2 %}
					selected="selected"
				{% endif %}
                >{{ man.name }}</option>
			{% endfor %}
</select></td></tr>

<tr><th><label for="id_amodel">Модель:</label></th><td>{{ form.amodel }}</td></tr>
<tr><th><label for="id_color">Цвет:</label></th><td>{{ form.color }}</td></tr>
<tr><th><label for="id_hp">Мощность:</label></th><td>{{ form.hp }}</td></tr>
<tr><th><label for="id_mfdate">Дата выпуска:</label></th><td>{{ form.mfdate }}</td></tr>
        </table>
        <input type="submit" value="Submit">
    </form>
<script type="text/javascript" charset="utf-8">
	FilterModels({{ model_id }});
</script>
{% if form.errors %}
Errors:<BR>
	{% for msg in form.message.errors %}
	{{ msg }}<BR>
	{% endfor %}
{% endif %}
</body>
</html>

templates/catalog.html
<html>
<head>
    <title>Каталог</title>
</head>
<body>
    <h1>Каталог</h1>
<ul>
{% for item in items %}
<li><a href="/catalog2/edit/{{ item.id }}/">{{ item }}</a> <a href="/catalog2/del/{{ item.id }}/">[x]</a></li>
{% endfor %}
<li><a href="/catalog2/add/">...</a></li>
</ul>
</body>
</html>

templates/catalog_edit.html
<html>
<head>
    <title>Каталог</title>
<style id="myStyles">
 .carsstyle {display:none; background-color:#999999}
 .trucksstyle {display:none; background-color:#999999}
 </style>

<script LANGUAGE="JavaScript" src="/prototype.js" type="text/javascript"></script>

<script language="javascript">
 <!--
 function SwitchType(){
 var typeList = $('id_type');
 var type = typeList.value;
 if (type == 0)
 {
    $('row1').style.display='none';
    $('row2').style.display='none';
    $('row3').style.display='';
    $('row4').style.display='';
    $('row5').style.display='';
 }
 else
 {
    $('row1').style.display='';
    $('row2').style.display='';
    $('row3').style.display='none';
    $('row4').style.display='none';
    $('row5').style.display='none';
 }
}
 // -->
 </script>

</head>
<body>
    <h1>Правка</h1>

    <form action="" method="post"><div style='display:none;'><input type='hidden' id='csrfmiddlewaretoken' name='csrfmiddlewaretoken' value='ded79cabad1980ee29c95f3e9005a70f' /></div>
{{ form.item_id }}
        <table>
            <tr><th><label for="id_type">Тип:</label></th><td><select name="type" id="id_type" onchange=SwitchType()>
				<option value= "0" {% if selected == 0 %} selected="selected" {% endif %}>Автомобиль</option>
				<option value= "1" {% if selected == 1 %} selected="selected" {% endif %}>Грузовик</option>
            <tr><th><label for="id_modelname">Производитель:</label></th><td>{{ form.modelname }}</td></tr>
<tr id = "row1" style="display:none"><th><label for="id_capacity">Грузоподъёмность:</label></th><td>{{ form.capacity }}</td></tr>
<tr id = "row2" style="display:none"><th><label for="id_horsepower">Сила:</label></th><td>{{ form.horsepower }}</td></tr>
<tr id = "row3" ><th><label for="id_body_type">Тип кузова:</label></th><td>{{ form.body_type }}</td></tr>
<tr id = "row4" ><th><label for="id_speed">Скорость:</label></th><td>{{ form.speed }}</td></tr>
<tr id = "row5" ><th><label for="id_doors">Количество дверей:</label></th><td>{{ form.doors }}</td></tr>

        </table>
        <input type="submit" value="Submit">
    </form>
<script type="text/javascript" charset="utf-8">
	SwitchType();
</script>
</body>
</html>

templates/fail.html
<html>
<head>
<title>Отчёт</title>
</head>
<body>
<h4>
Ошибка
</h4>
<a href="/">Вернуться в каталог</a>
</body>
</html>

templates/preview.html
<html>
<head>
<title>Просмотр</title>
</head>
<body>
{% load extras %}
<center>
{% if not no_items %}
<table BORDER="1" CELLSPACING="1" CELLPADDING="5" width="550" height = "550"><tr><td>
<IMG SRC="{{ viewimg.url }}" width="550">
</tr></td></table>
<table BORDER="1" CELLSPACING="1" CELLPADDING="5">
<tr>
{% for iimg in imglist %}
<td>
	<a href="/preview/{{ itm_id}}/{{ forloop.counter0 }}/">
		<IMG SRC="{{ iimg.thumb.url }}">
	</a>
</td>
  {% if not forloop.counter|mod:5 %}
    </tr><tr>
  {% endif %}
{% endfor %}
</tr>
</table>
{% else %}
	<h1>I'm sorry!</h1>
    No images found
{% endif %}
<hr>
<a href="/">Вернуться в Катáлог</a>
</center>
</body>
</html>

templates/start.html
<html>
<head>
<title>Главная страница</title>
</head>
<body>
<h1>
Катáлог
</h1>
<hr>
{% if username %}
  <form action="accounts/logout/" method="post"> {% csrf_token %}
	<label for="username">Hi, {{ username }}</label>
    <input type="submit" value="logout" />
    <input type="hidden" name="next" value="{{ next|escape }}" />
  </form>
{% else %}
  {% if form.errors %}
    <p class="error">Неправильный логин или пароль</p>
  {% endif %}
  <form action="accounts/login/" method='post'> {% csrf_token %}
    <label for="username">Логин:</label>
    <input type="text" name="username" value="" id="username">
    <label for="password">Пароль:</label>
    <input type="password" name="password" value="" id="password">

    <input type="submit" value="login" />
    <input type="hidden" name="next" value="{{ next|escape }}" />
  </form>
{% endif %}
<hr>
<P>   
	{% if text_enabled %}
	Результат поиска по запросу: {{ request }}
	<form action="/" method="get">
    <input type="submit" value="Сброс">
    </form>
	{% else %}
	Поиск
	<form action="/" method="get">
    <input type="text" name="q">
    <input type="submit" value="Поиск">
    </form>
	{% endif %}
</P>
<hr>
<table WIDTH="80%">
  <TR BGCOLOR=#CCCCCC>
    <TD ALIGN="CENTER" WIDTH="15%"><STRONG>Производитель</STRONG></TD>
    <TD ALIGN="CENTER" WIDTH="15%"><STRONG>Модель</STRONG></TD>
	<TD ALIGN="CENTER" WIDTH="15%"><STRONG>Год выпуска</STRONG></TD>
	<TD ALIGN="CENTER" WIDTH="15%"><STRONG>Цвет</STRONG></TD>
	<TD ALIGN="CENTER" WIDTH="15%"><STRONG>Мощность</STRONG></TD>
	<TD ALIGN="CENTER" WIDTH="13%"><STRONG>Фото</STRONG></TD>
{% if username %}
	<TD ALIGN="CENTER" WIDTH="12%"></TD>
{% endif %}
  </TR>
{% for item in aitems %}
  <TR BGCOLOR=#CCCCCC>
    <TD ALIGN="CENTER">{{ item.amodel.amanufact.name }}</TD>
    <TD ALIGN="CENTER">{{ item.amodel.name }}</TD>
	<TD ALIGN="CENTER">{{ item.mfdate|date:'Y-m-d' }}</TD>
	<TD ALIGN="CENTER">{{ item.color }}</TD>
	<TD ALIGN="CENTER">{{ item.hp }}</TD>
	<TD ALIGN="CENTER"><a href="preview/{{ item.id }}/0/">Просмотр</a></TD>
{% if username %}
	<TD ALIGN="CENTER">
		<form action="/edit/itm/" method="get">
		<input name="item_id" type="hidden" value="{{ item.id }}" />
		<input type="submit" value="Правка">
    	</form>
		<form action="/delete/itm/" method="get">
		<input name="item_id" type="hidden" value="{{ item.id }}" />
		<input type="submit" value="Удалить">
    	</form>
	</TD>
{% endif %}
  </TR>
{% endfor %}
</table>
{% if username %}
<table  WIDTH="80%">
  <TR BGCOLOR=#CCCCCC>
    <TD ALIGN="CENTER" WIDTH="15%">
		<form action="/add/man/" method="get">
    	{# <input type="submit" value="Добавить"> #}
    	</form>
	</TD>
    <TD ALIGN="CENTER" WIDTH="15%">
		<form action="/add/mod/" method="get">
    	{# <input type="submit" value="Добавить"> #}
    	</form>
	</TD>
	<TD ALIGN="CENTER">
		<form action="/add/itm/" method="get">
    	<input type="submit" value="Добавить наименование">
    	</form>
	</TD>
  </TR>
</table>
{% endif %}
<hr>
<a href="/catalog2/">Ещё каталог</a>
<hr>
<center>Time: {{current_date}} <br> <a href="/admin/">админка</a></center>
</body>
</html>

templates/success.html
<html>
<head>
<title>Отчёт</title>
</head>
<body>
<h4>
Операция завершена
</h4>
<a href="/">Вернуться в каталог</a>
</body>
</html>